server:
  port: 8082

spring:
  application:
    name: notification-service

  mail:
    host: localhost
    port: 1025
    username: test@example.com
    password: test
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

app:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-service-group
      user-events-topic: user-events
      auto-offset-reset: earliest

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/