spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/user_service_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

app:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      user-events-topic: user-events